### ISSUE TITLE
Codalab output file(mentioned in the leaderboard) style is not the same as out put in multirc human's out put file

### ISSUE THREAD

**Issue by zhipengChen** [CogComp/multirc#1]
{"pid":"News/CNN/cnn-3b5bbf3ba31e4775140f05a8b59db55b22ee3e63.txt","qid":"0","scores":[1,0,0,1,0]},

different with below

{
 "WH_dev_1639": "best",
 "WH_dev_3121": "united kingdom",
 "WH_dev_844": "horror",
 "WH_dev_612": "canada",
 "WH_dev_2211": "13",
 "WH_dev_1956": "kuwait",
 "WH_dev_2779": "rome",
 "WH_dev_3432": "edwards air force base",
 "WH_dev_2655": "rock",
 "WH_dev_4437": "santa cruz",

**Comment by danyaljj** [comment]
Should be fixed now.

**Comment by zhipengChen** [comment]
Thank you !

**Comment by zhipengChen** [comment]
![image](https://user-images.githubusercontent.com/13817269/43558770-b6fc771c-963d-11e8-8cb9-755e94ef7547.png)
this bundle can't added

**Comment by danyaljj** [comment]
Ah you're right. 
Should be fixed now. 
Can you double-check it now?
