### ISSUE TITLE
Some problem on MultiRC codalab

### ISSUE THREAD

**Issue by zhipengChen** [CogComp/multirc#5]
1、
![image](https://user-images.githubusercontent.com/13817269/43558828-f7242560-963d-11e8-8039-125e78b88093.png)
those bundle can't find!
2、
![image](https://user-images.githubusercontent.com/13817269/43558897-35afed14-963e-11e8-9435-6214cbf1910a.png)
this dev predicted file style is steal not the same as given example!

**Comment by danyaljj** [comment]
@zhipengChen 

I think I have fixed the issues. Can you check?
